import type { DbcMessage, DbcSignal } from './types'

export function createMessage(partial?: Partial<DbcMessage>): DbcMessage {
  return {
    id: crypto.randomUUID(),
    name: partial?.name ?? 'NewMessage',
    canId: partial?.canId ?? 0x100,
    dlc: partial?.dlc ?? 8,
    isExtended: partial?.isExtended ?? false,
    signals: partial?.signals ?? [],
  }
}

export function createSignal(partial?: Partial<DbcSignal>): DbcSignal {
  return {
    id: crypto.randomUUID(),
    name: partial?.name ?? 'NewSignal',
    startBit: partial?.startBit ?? 0,
    length: partial?.length ?? 8,
    byteOrder: partial?.byteOrder ?? 'intel',
    sign: partial?.sign ?? 'unsigned',
    factor: partial?.factor ?? 1,
    offset: partial?.offset ?? 0,
    minimum: partial?.minimum ?? 0,
    maximum: partial?.maximum ?? 255,
    unit: partial?.unit ?? '',
  }
}

function sanitizeName(name: string): string {
  const cleaned = name.trim().replace(/[^A-Za-z0-9_]/g, '_')
  return cleaned || 'Signal'
}

function canIdForDbc(canId: number, isExtended: boolean): number {
  return isExtended ? canId | 0x80000000 : canId
}

export function buildDbc(messages: DbcMessage[], dbName = 'SkillLogger'): string {
  const lines: string[] = [
    'VERSION ""',
    '',
    'NS_ :',
    '\tNS_DESC_',
    '\tCM_',
    '\tBA_DEF_',
    '\tBA_',
    '\tVAL_',
    '\tCAT_DEF_',
    '\tCAT_',
    '\tFILTER',
    '\tBA_DEF_DEF_',
    '\tEV_DATA_',
    '\tENVVAR_DATA_',
    '\tSGTYPE_',
    '\tSGTYPE_VAL_',
    '\tBA_DEF_SGTYPE_',
    '\tBA_SGTYPE_',
    '\tSIG_TYPE_REF_',
    '\tVAL_TABLE_',
    '\tSIG_GROUP_',
    '\tSIG_VALTYPE_',
    '\tSIGTYPE_VALTYPE_',
    '\tBO_TX_BU_',
    '\tBA_DEF_REL_',
    '\tBA_REL_',
    '\tBA_DEF_DEF_REL_',
    '\tBU_SG_REL_',
    '\tBU_EV_REL_',
    '\tBU_BO_REL_',
    '\tSG_MUL_VAL_',
    '',
    'BS_:',
    '',
    'BU_: Vector__XXX',
    '',
  ]

  for (const msg of messages) {
    const msgName = sanitizeName(msg.name)
    const id = canIdForDbc(msg.canId, msg.isExtended)
    lines.push(`BO_ ${id} ${msgName}: ${msg.dlc} Vector__XXX`)
    for (const sig of msg.signals) {
      const sigName = sanitizeName(sig.name)
      const endian = sig.byteOrder === 'intel' ? 1 : 0
      const sign = sig.sign === 'signed' ? '-' : '+'
      const unit = sig.unit.replace(/"/g, '')
      lines.push(
        ` SG_ ${sigName} : ${sig.startBit}|${sig.length}@${endian}${sign} (${sig.factor},${sig.offset}) [${sig.minimum}|${sig.maximum}] "${unit}" Vector__XXX`,
      )
    }
    lines.push('')
  }

  lines.push(`CM_ "Generated by ${dbName}";`)
  lines.push('')
  return lines.join('\n')
}

const STORAGE_KEY = 'skilllogger.dbc.messages'

export function loadMessages(): DbcMessage[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return defaultMessages()
    const parsed = JSON.parse(raw) as DbcMessage[]
    return Array.isArray(parsed) && parsed.length ? parsed : defaultMessages()
  } catch {
    return defaultMessages()
  }
}

export function saveMessages(messages: DbcMessage[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(messages))
}

export function defaultMessages(): DbcMessage[] {
  return [
    createMessage({
      name: 'EngineData',
      canId: 0x100,
      dlc: 8,
      signals: [
        createSignal({
          name: 'EngineSpeed',
          startBit: 0,
          length: 16,
          byteOrder: 'intel',
          factor: 0.25,
          offset: 0,
          minimum: 0,
          maximum: 8000,
          unit: 'rpm',
        }),
        createSignal({
          name: 'CoolantTemp',
          startBit: 16,
          length: 8,
          byteOrder: 'intel',
          factor: 1,
          offset: -40,
          minimum: -40,
          maximum: 215,
          unit: 'degC',
        }),
        createSignal({
          name: 'Throttle',
          startBit: 24,
          length: 8,
          byteOrder: 'intel',
          factor: 0.4,
          offset: 0,
          minimum: 0,
          maximum: 100,
          unit: '%',
        }),
      ],
    }),
    createMessage({
      name: 'VehicleStatus',
      canId: 0x200,
      dlc: 8,
      signals: [
        createSignal({
          name: 'VehicleSpeed',
          startBit: 0,
          length: 8,
          byteOrder: 'intel',
          factor: 1,
          offset: 0,
          minimum: 0,
          maximum: 255,
          unit: 'km/h',
        }),
      ],
    }),
  ]
}
